openapi: 3.1.0
info:
  title: RPC
  version: "1.0"
paths:
  /ethereum/{apiKey}:
    $ref: "rpc/paths/ethereum.yml#/paths/~1eth_accounts~1${apiKey}"
  /algorand/{apiKey}:
    $ref: "rpc/paths/algorand.yml#/paths/~1eth_accounts~1${apiKey}"
