openapi: 3.1.0
info:
  title: RPC
  version: "1.0"
paths:
  /eth_accounts/{apiKey}:
    $ref: "rpc/operations/eth/accounts.yml"
  /alg_accounts/{apiKey}:
    $ref: "rpc/operations/alg/accounts.yml"
  /eth_version:
    $ref: "rpc/operations/eth/version.yml"
  /alg_version:
    $ref: "rpc/operations/alg/version.yml"
