openapi: 3.1.0
info:
  title: Ethereum
  version: "1.0"
paths:
  /eth_accounts/${apiKey}:
    post:
      summary: eth_accounts - Ethereum
      description: Returns a list of addresses owned by client. Since Alchemy does not store keys, this will always return empty.
      tags: ["ethereum"]
      parameters:
        - name: apiKey
          in: path
          schema:
            type: string
            default: docs-demo
            description: |
              <style>
                .custom-style {
                  color: #048FF4;
                }
              </style>
              For higher throughput, <span class="custom-style"><a href="https://alchemy.com/?a=docs-demo" target="_blank">create your own API key</a></span>
          required: true
      operationId: eth-accounts
  /eth_version:
    post:
      summary: eth_version - Ethereum
      description: Returns version or something.
      tags: ["ethereum"]
      operationId: eth-version
